#!/usr/bin/env bash

# Remove existing images
rm -rf img

# Make the directories
mkdir -p img
mkdir -p iso
mkdir -p iso/EFI
mkdir -p iso/EFI/BOOT
mkdir -p iso/sys
mkdir -p iso/sys/core
mkdir -p iso/sys/sprg
mkdir -p iso/sys/res

# Copy the bootloader/boot config
cp res/limine.efi iso/EFI/BOOT/BOOTX64.EFI
cp res/limine.cfg iso/limine.cfg

# Copy the kernel
cp bin/kernel/mnk.elf iso/sys/core/mnk.elf

# Copy MNSH
cp bin/mnsh/mnsh.elf iso/sys/sprg/mnsh.elf

# Generate the FAT image
res/dir2fat32.sh img/micron.fat 260 iso

# Generate the ISO
xorriso -as mkisofs -R -f -no-emul-boot -o stdio:img/micron.iso iso

# Clean up
rm -rf iso