#!/usr/bin/env bash

# Generate an image
dd if=/dev/zero of=fat.img bs=1k count=1440

# Format the image
mformat -i fat.img -f 1440 ::

# Make the directories
mmd -i fat.img ::/EFI
mmd -i fat.img ::/EFI/BOOT
mmd -i fat.img ::/sys
mmd -i fat.img ::/sys/core

# Copy the bootloader
mcopy -i fat.img "$2" ::/EFI/BOOT/BOOTX64.EFI

# Copy the kernel
mcopy -i fat.img "$1" ::/sys/core/microCORE.kernel

# Generate the ISO
mkdir iso
cp fat.img iso
xorriso -as mkisofs -R -f -e fat.img -no-emul-boot -o microNET.iso iso

# Clean up
rm -rf iso fat.img