constexpr char *logo =
        "$WHITE!\n\n"
		"    /==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==\\\n"
  		"    |                                                              |\n"
        "    |$LIGHT_MAGENTA!                                .dh.        hd`               $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                                -MMN+       MM-               $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                  /-      `/.   -MNoMd.     MM-               $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                 -MN      oMh   -MN .dN+    MM-               $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                 -MN      oMh   -MN   oMd.  MM-               $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                 :MN      oMh   -MN    .dN+ MM-               $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                 -MM-     yMh   -MN      oMdMM-               $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                 -MMNho+odMMh   -MN       .dMM-               $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                 -MN`/os+-.o-   `+/         /+                $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                 -MN                                          $WHITE!|$WHITE!\n"
        "    |$LIGHT_MAGENTA!                 .Nd                                          $WHITE!|$WHITE!\n"
		"    |                                                              |\n"
        "    \\==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==/\n";